forge "https://forge.puppetlabs.com"

mod 'daenney-circus'
mod 'jfryman-nginx'
mod 'puppetlabs-apt'
mod 'puppetlabs-postgresql'
mod 'puppetlabs-rabbitmq'
mod 'puppetlabs-vcsrepo'
mod 'stankevich-python'
mod 'thomasvandoren-redis'

mod 'genome-ptero',
    :path => './ptero'
