forge "https://forge.puppetlabs.com"

mod 'jfryman-nginx'
mod 'puppetlabs-postgresql'
mod 'puppetlabs-rabbitmq'
mod 'puppetlabs-vcsrepo'
mod 'stankevich-python'

mod 'genome-ptero',
    :path => './ptero'
