# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "puppetlabs/ubuntu-14.04-64-puppet"
  config.vm.network "private_network", ip: ENV['PTERO_IP'] || "192.168.10.10"

  config.vm.provider "virtualbox" do |vb|
    # Use VBoxManage to customize the VM. For example to change memory:
    vb.customize ["modifyvm", :id, "--memory", "4096"]
    vb.customize ["modifyvm", :id, "--cpus",   "4"]
    vb.customize ["modifyvm", :id, "--ioapic", "on"]

  end

  config.librarian_puppet.puppetfile_dir = 'puppet'
  config.librarian_puppet.placeholder_filename = '.ALLINONE_VAGRANT_PLACEHOLDER'

  config.vm.provision :puppet do |puppet|
    puppet.manifests_path = 'puppet/manifests'
    puppet.manifest_file = 'allinone.pp'
    puppet.module_path = 'puppet/modules'

    puppet.hiera_config_path = './hiera-conf.yaml'
    puppet.temp_dir = '/tmp/vagrant-puppet'
    puppet.working_directory = '/tmp/vagrant-puppet'

    # For debugging
#    puppet.options = "--verbose --debug"
  end
end
