# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "puppetlabs/ubuntu-14.04-64-puppet"
  config.vm.network "private_network", ip: ENV['DEVSTACK_IP'] || "192.168.50.50"

  config.vm.provider "virtualbox" do |vb|
    # Use VBoxManage to customize the VM. For example to change memory:
    vb.customize ["modifyvm", :id, "--memory", "4096"]
    vb.customize ["modifyvm", :id, "--cpus",   "4"]
    vb.customize ["modifyvm", :id, "--ioapic", "on"]

  end

  config.vm.provision :puppet do |puppet|
    puppet.facter = {
      "fixedrange" => ENV['FIXED_RANGE'] || "172.16.0.0/13",
      "fixednetworksize" => ENV['FIXED_NETWORK_SIZE'] || "256",
      "floatingrange" => ENV['FLOATING_RANGE'] || "172.24.0.0/13",
      "networkgateway" => ENV['NETWORK_GATEWAY'] || "172.16.0.1",
    }

    puppet.manifests_path = 'puppet/manifests'
    puppet.manifest_file = 'site.pp'
    puppet.module_path = 'puppet/modules'
  end
end
