#!/usr/bin/env bash

CONFIG="$1"

SERVICE="\"$(pwd | xargs basename)\""

if [ $(jq ".services?.${SERVICE}|type|@text" "${CONFIG}") = '"null"' ]; then
    echo "Failed to find configuration for service ${SERVICE} in config file ${COFNIG}" 1>&2
    exit 1
fi

deis ps:scale $(jq -r ".services.${SERVICE}.scale|with_entries(.key = .key + \"=\" + .value)|keys|@sh" "${CONFIG}" | sed s/\'//g)
