#!/usr/bin/env bash

set -e
source $PTERO_COMMON

USAGE_MESSAGE="Usage: $0 DEPLOYMENT_CONFIG COMMAND"
DEPLOYMENT_CONFIG=${1?"$USAGE_MESSAGE"}
COMMAND=${2?"$USAGE_MESSAGE"}

for SERVICE in $(jq '.services | keys | .[]' $DEPLOYMENT_CONFIG); do
    eval $COMMAND $SERVICE
done
