#!/usr/bin/env bash

set -e
source $PTERO_COMMON

CONFIG=${@: -1}

log "Scaling apps..."
log

"${PTERO_DIR}/ptero" deploy deis service-foreach $CONFIG "${PTERO_DIR}/ptero" deploy deis scale-service $CONFIG
