#!/usr/bin/env bash

set -e
source $PTERO_COMMON

USAGE_MESSAGE="Usage: $0 DEPLOYMENT_CONFIG APP_NAME"
DEPLOYMENT_CONFIG=${1?"$USAGE_MESSAGE"}
APP_NAME=${2?"$USAGE_MESSAGE"}

log "Stopping $APP_NAME..."

DEIS_SCALE_ARGS=$(jq -r '.services.'"\"${APP_NAME}\""'.scale | keys | .[] + "=0"' $DEPLOYMENT_CONFIG)
deis ps:scale $DEIS_SCALE_ARGS --app=$APP_NAME

log
