#!/usr/bin/env bash

source $PTERO_COMMON

if [ ! -f "$1" ]; then
    log "Must specify a configuration file"
    exit 1
fi

CONFIG_FILE=$(realpath $1)

log "Scaling apps..."
log

"${PTERO_DIR}/ptero" service foreach "${PTERO_DIR}/deployment/libexec/deis-service-scale" "${CONFIG_FILE}"
