#!/usr/bin/env bash

source ${PTERO_DIR}/deployment/libexec/workers-common
source ${PTERO_DIR}/deployment/libexec/lsf-workers-common

log "Launching a lsf-job-status-updater..."
celery worker -A ptero_lsf.implementation.celery_app --concurrency=$PTERO_LSF_WORKER_CONCURRENCY -Q update &
PID=$!
wait $PID
