#!/usr/bin/env bash

source $PTERO_COMMON

DEPLOYMENT_CONFIG=${1?"Usage: $0 DEPLOYMENT_CONFIG"}

log "Setting app configs..."
log

"${PTERO_DIR}/ptero" deploy deis service-foreach "${DEPLOYMENT_CONFIG}" "${PTERO_DIR}/deployment/libexec/deis-service-push" "${DEPLOYMENT_CONFIG}"
