#!/usr/bin/env bash

set -e
source $PTERO_COMMON

ARGS=($@)
CONFIG=${ARGS[0]}
SERVICE=${ARGS[1]}

log "Scaling $SERVICE..."

DEIS_SCALE_ARGS=$(jq -r '.services.'"\"${SERVICE}\""'.scale | to_entries | map("\(.key)=\(.value)") | .[]' $CONFIG)
deis ps:scale $DEIS_SCALE_ARGS --app=$SERVICE

log
