#!/usr/bin/env bash

source $PTERO_COMMON

verify_jq

if [ ! -f "$1" ]; then
    log "Must specify a configuration file"
    exit 1
fi

CONFIG_FILE=$(python_realpath $1)
SERVICE='"lsf"'

log "Setting up environment for lsf worker from config file: $CONFIG_FILE"

if [ $(jq ".services?.${SERVICE}|type|@text" ${CONFIG_FILE}) = '"null"' ]; then
    echo "Failed to find configuration for service ${SERVICE} in config file ${CONFIG_FILE}" 1>&2
    exit 1
fi

VARS=$(jq -r ".services.${SERVICE}.environment|with_entries(.key = .key + \"=\" + .value)|keys|@sh" "${CONFIG_FILE}" | sed s/\'//g)
WORKER_VARS=$(jq -r ".services.${SERVICE}.\"worker-environment\"|with_entries(.key = .key + \"=\" + .value)|keys|@sh" "${CONFIG_FILE}" | sed s/\'//g)


for env_var in "$VARS $WORKER_VARS"; do
    eval "export $env_var"
done

log "Launching a lsf-job-status-updater..."
celery worker -A ptero_lsf.implementation.celery_app --concurrency=$PTERO_LSF_WORKER_CONCURRENCY -Q update
